// Generated by Haxe 4.3.7
#include <hxcpp.h>

namespace hx {
const char *__hxcpp_all_files[] = {
#ifdef HXCPP_DEBUGGER
"/usr/share/haxe/std/IntIterator.hx",
"/usr/share/haxe/std/cpp/_std/Std.hx",
"/usr/share/haxe/std/cpp/_std/haxe/Log.hx",
"?",
"ApplicationMain.hx",
"Main.hx",
#endif
 0 };

const char *__hxcpp_all_files_fullpath[] = {
#ifdef HXCPP_DEBUGGER
"/usr/share/haxe/std/IntIterator.hx",
"/usr/share/haxe/std/cpp/_std/Std.hx",
"/usr/share/haxe/std/cpp/_std/haxe/Log.hx",
"/home/jonk/Documentos/Coding/hexagon/test/?",
"/home/jonk/Documentos/Coding/hexagon/test/export/helper/ApplicationMain.hx",
"/home/jonk/Documentos/Coding/hexagon/test/src/Main.hx",
#endif
 0 };

const char *__hxcpp_all_classes[] = {
#ifdef HXCPP_DEBUGGER
"ApplicationMain",
"IntIterator",
"Main",
"Std",
"haxe.Log",
#endif
 0 };
} // namespace hx
void __files__boot() { __hxcpp_set_debugger_info(::hx::__hxcpp_all_classes, ::hx::__hxcpp_all_files_fullpath); }
