// Generated by Haxe 4.3.7
(function ($global) { "use strict";
var ApplicationMain = function() { };
ApplicationMain.main = function() {
	new Main();
};
var Main = function() {
	console.log("src/Main.hx:5:","aea");
};
var haxe_iterators_ArrayIterator = function(array) {
	this.current = 0;
	this.array = array;
};
haxe_iterators_ArrayIterator.prototype = {
	hasNext: function() {
		return this.current < this.array.length;
	}
	,next: function() {
		return this.array[this.current++];
	}
};
ApplicationMain.main();
})({});
